---

- name: Install packer and generate an image
  hosts: all

  tasks:

    - name: Install EPEL GPG keys for dnf
      ansible.builtin.rpm_key:
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-10

    - name: Enable EPEL on RHEL host
      become: true
      when: ansible_distribution == "RedHat"
      ansible.builtin.package:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
        state: present

    - name: Create Hashicorp repo
      become: true
      ansible.builtin.yum_repository:
        name: HashiCorp
        description: HashiCorp YUM repo
        baseurl: https://rpm.releases.hashicorp.com/RHEL/9/$basearch/stable
        # baseurl: https://rpm.releases.hashicorp.com/RHEL/{{ ansible_distribution_major_version }}/$basearch/stable
        gpgcheck: false
        enabled: true

    - name: Install packer package
      become: true
      ansible.builtin.package:
        name: packer
        state: present

    - name: Install Packer HCL to managed host
      ansible.builtin.copy:
        src: packer-ansible.zip
        dest: "{{ ansible_user_dir }}"
        mode: '0644'

    - name: Extract Packer HCL
      ansible.builtin.unarchive:
        src: '{{ ansible_user_dir }}/packer-ansible.zip'
        dest: "{{ ansible_user_dir }}"
        remote_src: true

    - name: Run Packer init
      ansible.builtin.command:
        chdir: '{{ ansible_user_dir }}/packer-ansible/'
        cmd: packer init rhel-10.pkr.hcl

    - name: Run Packer build
      ansible.builtin.command:
        chdir: '{{ ansible_user_dir }}/packer-ansible/'
        cmd: packer build -on-error=abort rhel-10.pkr.hcl
