---

- name: Install packer and generate an image
  hosts: all

  tasks:

    - name: Enable EPEL on RHEL host
      become: true
      when: ansible_distribution == "Red Hat Enterprise Linux"
      ansible.builtin.package:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
        state: present

    - name: Create Hashicorp repo
      become: true
      ansible.builtin.yum_repository:
        name: HashiCorp
        description: HashiCorp YUM repo
        baseurl: https://rpm.releases.hashicorp.com/RHEL/9/$basearch/stable
        # baseurl: https://rpm.releases.hashicorp.com/RHEL/{{ ansible_distribution_major_version }}/$basearch/stable
        gpgcheck: false
        enabled: true

    - name: Install packer package
      become: true
      ansible.builtin.package:
        name: packer
        state: present
